# Change these first
owner: pitgrap # Your GitHub username
repo: upptime-status # Your Github repository name

# Add your sites here
sites:
  - name: Server 1
    url: https://server1.riehemann.net
  - name: Server 2
    url: https://server2.riehemann.net

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.riehemann.net
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Riehemann IT Consulting
  introTitle: "**Server Status**"
  # introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  customBodyHtml: "<!-- Matomo --><script>var _paq = window._paq = window._paq || [];  _paq.push(['trackPageView']);  _paq.push(['enableLinkTracking']);  (function() {    var u='https://piwik.riehemann.net/';    _paq.push(['setTrackerUrl', u+'matomo.php']);    _paq.push(['setSiteId', '21']);    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0]; g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s); })();</script><!-- End Matomo Code -->"
  navbar:
    - title: Home
      href: https://www.riehemann-it.de/
    - title: Status
      href: /
