# Change these first
owner: pitgrap # Your GitHub username
repo: upptime-status # Your Github repository name

# Add your sites here
sites:
  - name: Server 1
    url: https://server1.riehemann.net
  - name: Server 2
    url: https://server2.riehemann.netg

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname:status.riehemann.net
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Riehemann IT Consulting - Server Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/pitgrap/upptime-status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
